"""add_missing_business_columns

Revision ID: 0a32bc6faee8
Revises: b2df0aadab30
Create Date: 2025-09-06 14:12:46.484963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a32bc6faee8'
down_revision: Union[str, None] = 'b2df0aadab30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('zoho_organization_id', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('default_currency', sa.String(length=10), nullable=True))
    op.add_column('businesses', sa.Column('setup_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('webhook_config', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('ebm_service_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_businesses_zoho_organization_id'), 'businesses', ['zoho_organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_zoho_organization_id'), table_name='businesses')
    op.drop_column('businesses', 'ebm_service_url')
    op.drop_column('businesses', 'webhook_config')
    op.drop_column('businesses', 'setup_completed_at')
    op.drop_column('businesses', 'default_currency')
    op.drop_column('businesses', 'zoho_organization_id')
    # ### end Alembic commands ###
